"use client";

import * as React from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Printer } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import malkhanaApi from "@/lib/api/malkhana";
import { Button, buttonVariants } from "@/components/ui/button";
import { officerMessage } from "../../parts";

/**
 * Printable property label. The QR code is generated by the API from the
 * property number and its verification address only.
 */
export default function PropertyLabelPage() {
  const { t } = useI18n();
  const { id } = useParams<{ id: string }>();
  const label = useQuery({ queryKey: ["malkhana", "item", id, "label"], queryFn: () => malkhanaApi.label(id), enabled: Boolean(id) });

  return (
    <main className="mx-auto flex min-h-screen max-w-md flex-col gap-4 bg-background p-6 print:max-w-none print:p-0">
      <div className="flex items-center justify-between gap-2 print:hidden">
        <Link href={`/malkhana/${id}`} className={buttonVariants({ variant: "outline", size: "sm" })}>
          <ArrowLeft className="h-4 w-4" />
          {t("malkhanaScreen.actions.back")}
        </Link>
        <Button size="sm" onClick={() => window.print()} disabled={!label.data} data-testid="print-label">
          <Printer className="h-4 w-4" />
          {t("malkhanaScreen.actions.print")}
        </Button>
      </div>

      {label.isLoading ? (
        <p className="text-sm text-foreground-muted">…</p>
      ) : label.isError || !label.data ? (
        <p className="text-sm text-danger">
          {t("malkhanaScreen.label.loadFailed")}: {officerMessage(label.error)}
        </p>
      ) : (
        <section
          className="flex flex-col items-center gap-2 rounded-lg border-2 border-black bg-white p-4 text-black"
          data-testid="property-label"
        >
          <p className="text-xs font-semibold uppercase tracking-wide">{label.data.stationName} · Malkhana</p>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={label.data.qrPng} alt={label.data.propertyNumber} width={200} height={200} data-testid="label-qr" />
          <p className="font-mono text-lg font-bold">{label.data.propertyNumber}</p>
          <dl className="grid w-full grid-cols-2 gap-x-3 gap-y-1 text-xs">
            <dt className="font-semibold">{t("malkhanaScreen.table.category")}</dt>
            <dd>{t(`malkhanaScreen.category.${label.data.category}`)}</dd>
            <dt className="font-semibold">{t("malkhanaScreen.item.seal")}</dt>
            <dd className="font-mono">{label.data.sealNumber}</dd>
            <dt className="font-semibold">{t("malkhanaScreen.item.location")}</dt>
            <dd>{label.data.locationLabel || "—"}</dd>
            <dt className="font-semibold">{t("malkhanaScreen.table.record")}</dt>
            <dd className="font-mono">{[label.data.caseNumber, label.data.firNumber && `FIR ${label.data.firNumber}`].filter(Boolean).join(" · ") || "—"}</dd>
          </dl>
          <p className="mt-1 break-all text-center font-mono text-[0.6rem]" data-testid="label-url">{label.data.verifyUrl}</p>
        </section>
      )}
      <p className="text-xs text-foreground-muted print:hidden">{t("malkhanaScreen.label.scanHint")}</p>
    </main>
  );
}
