import type { ChallanStatus, ChallanVehicleType } from "@/lib/api/traffic-challans";

type T = { en: string; bn: string };

/** Traffic challan screen strings. */
export const TL = {
  title: { en: "Traffic challans", bn: "ট্রাফিক চালান" },
  description: {
    en: "E-challans issued under the Motor Vehicles Act. Payments are recorded by officers against the receipt; no payment gateway is connected.",
    bn: "মোটর যান আইনে জারি করা ই-চালান। জরিমানা প্রদান রসিদ দেখে আধিকারিক নথিভুক্ত করেন; কোনো পেমেন্ট গেটওয়ে যুক্ত নেই।",
  },
  issue: { en: "Issue challan", bn: "চালান জারি করুন" },
  defaulters: { en: "Defaulters", bn: "বকেয়াদার" },
  register: { en: "Challan register", bn: "চালান নিবন্ধন" },
  total: { en: "Challans issued", bn: "জারি হওয়া চালান" },
  totalAmount: { en: "Fines imposed", bn: "আরোপিত জরিমানা" },
  collected: { en: "Recorded as paid", bn: "প্রদত্ত হিসেবে নথিভুক্ত" },
  pending: { en: "Outstanding", bn: "বকেয়া" },
  searchVehicle: { en: "Vehicle registration…", bn: "গাড়ির রেজিস্ট্রেশন…" },
  allStatuses: { en: "All statuses", bn: "সব অবস্থা" },
  number: { en: "Challan", bn: "চালান" },
  vehicle: { en: "Vehicle", bn: "গাড়ি" },
  violation: { en: "Violation", bn: "লঙ্ঘন" },
  location: { en: "Location", bn: "স্থান" },
  date: { en: "Date", bn: "তারিখ" },
  amount: { en: "Amount", bn: "পরিমাণ" },
  status: { en: "Status", bn: "অবস্থা" },
  loading: { en: "Loading challans…", bn: "চালান লোড হচ্ছে…" },
  loadFailed: { en: "Challans could not be loaded", bn: "চালান লোড করা যায়নি" },
  retry: { en: "Try again", bn: "আবার চেষ্টা করুন" },
  empty: { en: "No challans match", bn: "কোনো চালান মেলেনি" },
  emptyBody: { en: "Challans appear here once issued.", bn: "জারি হলে চালান এখানে দেখা যাবে।" },
  prev: { en: "Previous", bn: "আগের" },
  next: { en: "Next", bn: "পরের" },
  page: { en: "Page", bn: "পৃষ্ঠা" },
  topViolations: { en: "Most frequent violations", bn: "সবচেয়ে বেশি লঙ্ঘন" },
  back: { en: "Back", bn: "ফিরে যান" },
  notFound: { en: "Challan not found", bn: "চালান পাওয়া যায়নি" },
  notFoundBody: { en: "The requested challan does not exist.", bn: "অনুরোধ করা চালানটি নেই।" },
  backToRegister: { en: "Back to challans", bn: "চালানে ফিরে যান" },
  vehicleDetails: { en: "Vehicle and driver", bn: "গাড়ি ও চালক" },
  violationDetails: { en: "Violation", bn: "লঙ্ঘন" },
  fine: { en: "Fine", bn: "জরিমানা" },
  original: { en: "Fine imposed", bn: "আরোপিত জরিমানা" },
  discount: { en: "Discount", bn: "ছাড়" },
  penalty: { en: "Late penalty", bn: "বিলম্ব জরিমানা" },
  finalAmount: { en: "Amount payable", bn: "প্রদেয় পরিমাণ" },
  due: { en: "Payment due", bn: "প্রদানের শেষ তারিখ" },
  paidOn: { en: "Paid on", bn: "প্রদানের তারিখ" },
  reference: { en: "Receipt / order reference", bn: "রসিদ / আদেশের সূত্র" },
  issuedBy: { en: "Issued by", bn: "জারি করেছেন" },
  section: { en: "Section", bn: "ধারা" },
  owner: { en: "Owner", bn: "মালিক" },
  driver: { en: "Driver", bn: "চালক" },
  licence: { en: "Driving licence", bn: "ড্রাইভিং লাইসেন্স" },
  phone: { en: "Phone", bn: "ফোন" },
  make: { en: "Make", bn: "প্রস্তুতকারক" },
  model: { en: "Model", bn: "মডেল" },
  colour: { en: "Colour", bn: "রং" },
  seizure: { en: "vehicle may be seized", bn: "গাড়ি আটক হতে পারে" },
  type: { en: "Vehicle type", bn: "গাড়ির ধরন" },
  details: { en: "Description", bn: "বিবরণ" },
  dispute: { en: "Dispute", bn: "আপত্তি" },
  disputeReason: { en: "Grounds of dispute", bn: "আপত্তির কারণ" },
  recordDispute: { en: "Record dispute", bn: "আপত্তি নথিভুক্ত করুন" },
  actions: { en: "Actions", bn: "পদক্ষেপ" },
  changeStatus: { en: "Record outcome", bn: "ফলাফল নথিভুক্ত করুন" },
  newStatus: { en: "New status", bn: "নতুন অবস্থা" },
  note: { en: "Reason", bn: "কারণ" },
  save: { en: "Save", bn: "সংরক্ষণ" },
  cancel: { en: "Cancel", bn: "বাতিল" },
  noActions: { en: "No further action is possible on a challan in this status.", bn: "এই অবস্থার চালানে আর কোনো পদক্ষেপ সম্ভব নয়।" },
  actionsRestricted: { en: "Recording outcomes needs SI rank or above.", bn: "ফলাফল নথিভুক্ত করতে এসআই বা ঊর্ধ্বতন পদ প্রয়োজন।" },
  referenceRequired: { en: "Receipt or compounding order reference", bn: "রসিদ বা আপস আদেশের সূত্র" },
  saved: { en: "Challan updated", bn: "চালান হালনাগাদ হয়েছে" },
  failed: { en: "Not saved", bn: "সংরক্ষিত হয়নি" },
  issueTitle: { en: "Issue traffic challan", bn: "ট্রাফিক চালান জারি" },
  issueDescription: {
    en: "The fine is fixed by the violation type; the challan is recorded against your station.",
    bn: "জরিমানা লঙ্ঘনের ধরন অনুযায়ী নির্ধারিত; চালান আপনার থানার নামে নথিভুক্ত হয়।",
  },
  chooseViolation: { en: "Choose the violation", bn: "লঙ্ঘন বেছে নিন" },
  latitude: { en: "Latitude (optional)", bn: "অক্ষাংশ (ঐচ্ছিক)" },
  longitude: { en: "Longitude (optional)", bn: "দ্রাঘিমাংশ (ঐচ্ছিক)" },
  coordsPair: { en: "Give both latitude and longitude, or neither.", bn: "অক্ষাংশ ও দ্রাঘিমাংশ দুটোই দিন, অথবা কোনোটিই নয়।" },
  required: { en: "Violation, date, location, vehicle registration and vehicle type are required.", bn: "লঙ্ঘন, তারিখ, স্থান, গাড়ির রেজিস্ট্রেশন ও ধরন আবশ্যক।" },
  issued: { en: "Challan issued", bn: "চালান জারি হয়েছে" },
  issuing: { en: "Issuing…", bn: "জারি হচ্ছে…" },
  issueRestricted: { en: "Issuing challans needs constable rank or above.", bn: "চালান জারি করতে কনস্টেবল বা ঊর্ধ্বতন পদ প্রয়োজন।" },
  pendingChallans: { en: "Unpaid challans", bn: "অপ্রদত্ত চালান" },
  pendingAmount: { en: "Outstanding amount", bn: "বকেয়া পরিমাণ" },
  oldest: { en: "Oldest unpaid", bn: "প্রাচীনতম অপ্রদত্ত" },
  defaultersDescription: {
    en: "Vehicles with unpaid challans, as recorded by the challan register.",
    bn: "অপ্রদত্ত চালান থাকা গাড়ি, চালান নিবন্ধন অনুযায়ী।",
  },
  noDefaulters: { en: "No vehicles with unpaid challans", bn: "অপ্রদত্ত চালান থাকা কোনো গাড়ি নেই" },
  viewChallans: { en: "View challans", bn: "চালান দেখুন" },
};

export const STATUS_LABEL: Record<ChallanStatus, T> = {
  ISSUED: { en: "Issued", bn: "জারি" },
  PENDING: { en: "Pending", bn: "অপেক্ষমাণ" },
  PAID: { en: "Paid", bn: "প্রদত্ত" },
  DISPUTED: { en: "Disputed", bn: "আপত্তিকৃত" },
  CANCELLED: { en: "Cancelled", bn: "বাতিল" },
  COURT_REFERRED: { en: "Referred to court", bn: "আদালতে প্রেরিত" },
  COMPOUNDED: { en: "Compounded", bn: "আপসকৃত" },
  DEFAULTED: { en: "Defaulted", bn: "খেলাপি" },
};

export const STATUS_TONE: Record<ChallanStatus, "neutral" | "info" | "success" | "warning" | "danger"> = {
  ISSUED: "info",
  PENDING: "info",
  PAID: "success",
  DISPUTED: "warning",
  CANCELLED: "neutral",
  COURT_REFERRED: "warning",
  COMPOUNDED: "success",
  DEFAULTED: "danger",
};

export const VEHICLE_TYPE_LABEL: Record<ChallanVehicleType, T> = {
  TWO_WHEELER: { en: "Two-wheeler", bn: "দুই চাকার" },
  THREE_WHEELER: { en: "Three-wheeler", bn: "তিন চাকার" },
  FOUR_WHEELER: { en: "Four-wheeler", bn: "চার চাকার" },
  COMMERCIAL: { en: "Commercial", bn: "বাণিজ্যিক" },
  HEAVY_VEHICLE: { en: "Heavy vehicle", bn: "ভারী যান" },
  TRANSPORT: { en: "Transport", bn: "পরিবহন" },
  OTHER: { en: "Other", bn: "অন্যান্য" },
};

/** Amounts are stored in paise. */
export const rupees = (paise: number) =>
  `₹${(paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;
