"use client";

import { useState } from "react";
import { FileText, Download, Calendar, BarChart3, X, Printer } from "lucide-react";
import { Button } from "./button";
import { LegacySelect as Select } from "./select";

interface ReportData {
  totalFIRs: number;
  pendingCases: number;
  closedCases: number;
  officersOnDuty: number;
  criticalAlerts: number;
  evidenceItems: number;
  vehiclesActive: number;
  weaponsIssued: number;
}

interface ReportGeneratorDialogProps {
  isOpen: boolean;
  onClose: () => void;
  reportData: ReportData;
  stationName: string;
}

const reportTypes = [
  { value: "daily", label: "Daily Report" },
  { value: "weekly", label: "Weekly Report" },
  { value: "monthly", label: "Monthly Report" },
  { value: "fir_summary", label: "FIR Summary" },
  { value: "case_status", label: "Case Status Report" },
  { value: "personnel_duty", label: "Personnel Duty Report" },
];

export function ReportGeneratorDialog({
  isOpen,
  onClose,
  reportData,
  stationName,
}: ReportGeneratorDialogProps) {
  const [reportType, setReportType] = useState("daily");
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportGenerated, setReportGenerated] = useState(false);

  if (!isOpen) return null;

  const handleGenerate = async () => {
    setIsGenerating(true);
    // Simulate report generation
    await new Promise((resolve) => setTimeout(resolve, 1500));
    setIsGenerating(false);
    setReportGenerated(true);
  };

  const handleDownload = () => {
    // Create report content
    const reportContent = `
================================================================================
                         ${stationName.toUpperCase()}
                         ${reportTypes.find(r => r.value === reportType)?.label?.toUpperCase()}
================================================================================

Generated: ${new Date().toLocaleString()}
Report Period: ${new Date().toLocaleDateString()}

--------------------------------------------------------------------------------
                              SUMMARY STATISTICS
--------------------------------------------------------------------------------

FIR Statistics
--------------
  Total FIRs Registered:     ${reportData.totalFIRs}

Case Statistics
---------------
  Pending Cases:             ${reportData.pendingCases}
  Closed Cases:              ${reportData.closedCases}

Personnel Status
----------------
  Officers On Duty:          ${reportData.officersOnDuty}

Alert Status
------------
  Active Critical Alerts:    ${reportData.criticalAlerts}

Resources
---------
  Evidence Items in Custody: ${reportData.evidenceItems}
  Active Patrol Vehicles:    ${reportData.vehiclesActive}
  Weapons Currently Issued:  ${reportData.weaponsIssued}

--------------------------------------------------------------------------------
                              END OF REPORT
--------------------------------------------------------------------------------

Report generated by NPDMS - National Police Department Management System
    `.trim();

    // Create and download file
    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${stationName.replace(/\s+/g, "_")}_${reportType}_${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>${stationName} - ${reportTypes.find(r => r.value === reportType)?.label}</title>
            <style>
              body { font-family: 'Courier New', monospace; padding: 20px; }
              h1 { text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; }
              h2 { text-align: center; color: #666; }
              .stats { margin: 20px 0; }
              .stat-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px dashed #ccc; }
              .stat-label { font-weight: bold; }
              .section { margin: 30px 0; }
              .section-title { font-size: 14px; font-weight: bold; margin-bottom: 10px; background: #f0f0f0; padding: 5px; }
              .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #666; }
            </style>
          </head>
          <body>
            <h1>${stationName}</h1>
            <h2>${reportTypes.find(r => r.value === reportType)?.label}</h2>
            <p style="text-align: center;">Generated: ${new Date().toLocaleString()}</p>

            <div class="section">
              <div class="section-title">FIR & CASE STATISTICS</div>
              <div class="stats">
                <div class="stat-row"><span class="stat-label">Total FIRs:</span><span>${reportData.totalFIRs}</span></div>
                <div class="stat-row"><span class="stat-label">Pending Cases:</span><span>${reportData.pendingCases}</span></div>
                <div class="stat-row"><span class="stat-label">Closed Cases:</span><span>${reportData.closedCases}</span></div>
              </div>
            </div>

            <div class="section">
              <div class="section-title">PERSONNEL & RESOURCES</div>
              <div class="stats">
                <div class="stat-row"><span class="stat-label">Officers On Duty:</span><span>${reportData.officersOnDuty}</span></div>
                <div class="stat-row"><span class="stat-label">Active Vehicles:</span><span>${reportData.vehiclesActive}</span></div>
                <div class="stat-row"><span class="stat-label">Weapons Issued:</span><span>${reportData.weaponsIssued}</span></div>
              </div>
            </div>

            <div class="section">
              <div class="section-title">ALERTS & EVIDENCE</div>
              <div class="stats">
                <div class="stat-row"><span class="stat-label">Critical Alerts:</span><span>${reportData.criticalAlerts}</span></div>
                <div class="stat-row"><span class="stat-label">Evidence Items:</span><span>${reportData.evidenceItems}</span></div>
              </div>
            </div>

            <div class="footer">
              <p>NPDMS - National Police Department Management System</p>
              <p>This is a computer-generated report</p>
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const handleClose = () => {
    setReportGenerated(false);
    setReportType("daily");
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div className="fixed inset-0 bg-black/50" onClick={handleClose} />

      {/* Dialog */}
      <div className="relative bg-background-secondary border border-border rounded-lg shadow-xl w-full max-w-lg mx-4 p-6">
        <button
          onClick={handleClose}
          className="absolute top-4 right-4 text-foreground-muted hover:text-foreground"
        >
          <X className="h-5 w-5" />
        </button>

        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 rounded-full bg-accent/10">
            <BarChart3 className="h-6 w-6 text-accent" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-foreground">
              Generate Station Report
            </h2>
            <p className="text-sm text-foreground-muted">
              {stationName}
            </p>
          </div>
        </div>

        {!reportGenerated ? (
          <>
            <div className="space-y-4 mb-6">
              <Select
                label="Report Type"
                options={reportTypes}
                value={reportType}
                onChange={(v: string) => setReportType(v)}
              />

              <div className="p-4 rounded-lg bg-background-tertiary">
                <div className="flex items-center gap-2 text-foreground-muted mb-3">
                  <Calendar className="h-4 w-4" />
                  <span className="text-sm font-medium">Report Preview</span>
                </div>
                <div className="grid grid-cols-2 gap-3 text-sm">
                  <div className="flex justify-between">
                    <span className="text-foreground-muted">FIRs:</span>
                    <span className="font-medium text-foreground">{reportData.totalFIRs}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-foreground-muted">Pending Cases:</span>
                    <span className="font-medium text-foreground">{reportData.pendingCases}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-foreground-muted">Closed Cases:</span>
                    <span className="font-medium text-foreground">{reportData.closedCases}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-foreground-muted">Officers:</span>
                    <span className="font-medium text-foreground">{reportData.officersOnDuty}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-foreground-muted">Alerts:</span>
                    <span className="font-medium text-foreground">{reportData.criticalAlerts}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-foreground-muted">Evidence:</span>
                    <span className="font-medium text-foreground">{reportData.evidenceItems}</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex justify-end gap-3">
              <Button variant="ghost" onClick={handleClose}>
                Cancel
              </Button>
              <Button onClick={handleGenerate} disabled={isGenerating}>
                {isGenerating ? (
                  <>
                    <span className="animate-spin mr-2">...</span>
                    Generating...
                  </>
                ) : (
                  <>
                    <FileText className="h-4 w-4 mr-2" />
                    Generate Report
                  </>
                )}
              </Button>
            </div>
          </>
        ) : (
          <>
            <div className="p-6 rounded-lg bg-success/10 border border-success/30 mb-6">
              <div className="flex items-center gap-3 mb-3">
                <FileText className="h-8 w-8 text-success" />
                <div>
                  <p className="font-medium text-foreground">Report Generated Successfully</p>
                  <p className="text-sm text-foreground-muted">
                    {reportTypes.find(r => r.value === reportType)?.label} - {new Date().toLocaleDateString()}
                  </p>
                </div>
              </div>
            </div>

            <div className="flex justify-end gap-3">
              <Button variant="secondary" onClick={handlePrint}>
                <Printer className="h-4 w-4 mr-2" />
                Print
              </Button>
              <Button onClick={handleDownload}>
                <Download className="h-4 w-4 mr-2" />
                Download
              </Button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
